server:
  port: 8000

spring:
  application:
    name: springboot-base-study
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/base?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: studydocker1!
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        query.in_clause_parameter_padding: true
        show_sql: true
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs # api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /index.html # host/swagger-ui/{path}
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true


logging:
  level:
    org:
      hibernate:
        orm.jdbc.bind: trace # hibernate core 6.x
#        type.descriptor.sql.BasicBinder: trace # hibernate core 5.x


